#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Shilpa Narasimhan
Technical support: Codex (version GPT-5)
QA/Testing Responsibility: Shilpa
Creation date: 2026-03-03
Purpose of file: Plot R515A validation error bars for pressure and latent heat
from the generated verification CSV.
Dependencies: csv, pathlib, matplotlib, numpy
Context reference: PROJECT_CONTEXT.md

Version: v0.1.0

# BREADCRUMB:
# Date: 2026-03-03
# Assumptions:
# - Input CSV was generated by scripts/validate_r515a_saturation.py.
# - Reference row key is "reference_nist_tn2063_table7".
# - Comparison rows are "model_bubble_solver" and "model_dew_solver".
# TODO: Extend to multi-temperature validation points when available.
"""

from __future__ import annotations

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_rows(csv_path: Path) -> tuple[dict, list[dict]]:
    """
    Purpose
    -------
    Load reference and model rows from validation CSV.

    Inputs
    ------
    csv_path : Path [filesystem path]

    Outputs
    -------
    tuple[dict, list[dict]]
      Reference row dict and list of comparison model rows.

    Assumptions
    -----------
    CSV contains expected case labels.

    Failure modes
    -------------
    Raises ValueError if required rows are missing.

    References
    ----------
    Validation CSV schema from scripts/validate_r515a_saturation.py.

    Numerical stability notes
    -------------------------
    Not applicable.
    """
    with csv_path.open() as f:
        rows = list(csv.DictReader(f))
    ref = next((r for r in rows if r["case"] == "reference_nist_tn2063_table7"), None)
    cmp_rows = [r for r in rows if r["case"] in {"model_bubble_solver", "model_dew_solver"}]
    if ref is None or len(cmp_rows) != 2:
        raise ValueError("Missing required reference/model rows in validation CSV")
    return ref, cmp_rows


def plot_error_bars(csv_path: Path, out_path: Path) -> None:
    """
    Purpose
    -------
    Plot percent-error bars for pressure and latent heat against reference.

    Inputs
    ------
    csv_path : Path [filesystem path]
    out_path : Path [filesystem path]

    Outputs
    -------
    Saves one PNG figure [image file].

    Assumptions
    -----------
    Reference and model rows include p_kPa and hfg_kJkg values.

    Failure modes
    -------------
    Raises exceptions on file or parsing errors.

    References
    ----------
    Basic relative error definition: (model-reference)/reference.

    Numerical stability notes
    -------------------------
    Uses finite nonzero denominators from reference values.
    """
    ref, cmp_rows = load_rows(csv_path)

    p_ref = float(ref["p_kPa"])
    h_ref = float(ref["hfg_kJkg"])

    labels = []
    p_err = []
    h_err = []
    for r in cmp_rows:
        labels.append("Bubble" if "bubble" in r["case"] else "Dew")
        p_val = float(r["p_kPa"])
        h_val = float(r["hfg_kJkg"])
        p_err.append(100.0 * (p_val - p_ref) / p_ref)
        h_err.append(100.0 * (h_val - h_ref) / h_ref)

    x = np.arange(len(labels), dtype=float)
    width = 0.34

    fig, ax = plt.subplots(figsize=(7.2, 4.6), dpi=180)
    ax.axhline(0.0, color="black", lw=1.0, alpha=0.7)
    ax.bar(x - width / 2.0, p_err, width, label="Pressure error [%]", color="#1f77b4")
    ax.bar(x + width / 2.0, h_err, width, label="Latent heat error [%]", color="#ff7f0e")

    for xi, pe, he in zip(x, p_err, h_err):
        ax.text(xi - width / 2.0, pe + (0.15 if pe >= 0 else -0.45), f"{pe:.2f}%", ha="center", va="bottom" if pe >= 0 else "top", fontsize=8)
        ax.text(xi + width / 2.0, he + (0.15 if he >= 0 else -0.45), f"{he:.2f}%", ha="center", va="bottom" if he >= 0 else "top", fontsize=8)

    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylabel("Relative error [%]")
    ax.set_title("R515A Validation Error Bars at 277.6 K")
    ax.grid(True, axis="y", alpha=0.25)
    ax.legend()
    fig.tight_layout()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")


def main() -> None:
    """
    Purpose
    -------
    CLI entrypoint for plotting R515A validation error bars.

    Inputs
    ------
    None [unitless]

    Outputs
    -------
    Saves figure to verification/r515a_validation_error_bars.png.

    Assumptions
    -----------
    Validation CSV already exists.

    Failure modes
    -------------
    Raises exceptions if the CSV is missing or malformed.

    References
    ----------
    Project validation workflow.

    Numerical stability notes
    -------------------------
    Not applicable.
    """
    csv_path = Path("verification/r515a_saturation_validation_nist_tn2063.csv")
    out_path = Path("verification/r515a_validation_error_bars.png")
    plot_error_bars(csv_path, out_path)
    print(f"Saved: {out_path}")


if __name__ == "__main__":
    main()
